import { useState } from "react";
import { Badge, Button, EmptyState, ModalShell } from "../ui/index.jsx";
import { deriveDriverStatistics, driverDisplayName, emptyDriverProfile } from "./driverProfileUtils.js";

const fmtOdo = (value) => value == null ? "—" : new Intl.NumberFormat("en-US", { maximumFractionDigits: 3 }).format(value);
const Field = ({ label, children }) => <div><div className="text-[11px] font-semibold uppercase tracking-wide text-neutral-500">{label}</div><div className="mt-0.5 break-words text-sm text-neutral-800">{children || "—"}</div></div>;
const Stat = ({ label, value }) => <div className="rounded-lg border border-neutral-200 bg-white p-2"><div className="text-[10px] font-semibold uppercase tracking-wide text-neutral-500">{label}</div><div className="mt-0.5 font-semibold text-neutral-800">{value}</div></div>;

export function DriverProfiles({ drivers, vehicles, tripsByVehicle, onSave, onDuplicate, onToggleActive, onDelete, onViewTrip, initialExpandedId = null }) {
  const [expandedId, setExpandedId] = useState(initialExpandedId); const [editing, setEditing] = useState(null);
  return <section className="ts-card" aria-labelledby="driver-profiles-heading"><div className="ts-card__header flex items-center justify-between gap-3"><h2 id="driver-profiles-heading" className="font-semibold text-neutral-800">Driver Profiles</h2><Button variant="primary" onClick={() => setEditing(emptyDriverProfile())}>Add Driver</Button></div><div className="ts-card__body space-y-2">
    {!drivers.length ? <EmptyState title="No driver profiles" description="Profiles are also created automatically from historical leg drivers." /> : drivers.map((driver) => { const expanded = expandedId === driver.id; const stats = deriveDriverStatistics(driver, tripsByVehicle, vehicles); const panelId = `driver-profile-${driver.id}`; const defaultVehicle = vehicles.find((vehicle) => vehicle.id === driver.defaultVehicleId); return <article key={driver.id} className="overflow-hidden rounded-xl border border-neutral-200 bg-white"><button type="button" className="flex w-full items-start justify-between gap-3 p-3 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-lime-400" aria-expanded={expanded} aria-controls={panelId} onClick={() => setExpandedId(expanded ? null : driver.id)}><span className="min-w-0"><span className="flex flex-wrap items-center gap-2"><strong>{driverDisplayName(driver)}</strong><Badge variant={driver.active ? "success" : "default"}>{driver.active ? "Active" : "Inactive"}</Badge></span><span className="mt-1 block text-xs text-neutral-500">Default vehicle: {defaultVehicle?.name || "—"}</span><span className="mt-1 flex flex-wrap gap-3 text-xs text-neutral-600"><span>{stats.tripCount} trips</span><span>{stats.totalDistance.toFixed(1)} km</span><span>{stats.totalDriveTime}</span></span></span><span className="grid h-11 w-11 shrink-0 place-items-center" aria-hidden="true">{expanded ? "−" : "+"}</span></button>{expanded && <div id={panelId} className="space-y-4 border-t border-neutral-100 bg-neutral-50 p-3">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><ProfileSection title="Profile"><Field label="Name" children={driver.fullName} /><Field label="Display name" children={driver.displayName} /><Field label="Employee number" children={driver.employeeNumber} /></ProfileSection><ProfileSection title="Contact"><Field label="Phone" children={driver.phone} /><Field label="Email" children={driver.email} /></ProfileSection><ProfileSection title="Licence"><Field label="Number" children={driver.licenceNumber} /><Field label="Country" children={driver.licenceCountry} /><Field label="Expiry" children={driver.licenceExpiry} /></ProfileSection><ProfileSection title="Employment"><Field label="Start date" children={driver.startDate} /></ProfileSection><ProfileSection title="Vehicle"><Field label="Default vehicle" children={defaultVehicle?.name} /></ProfileSection><ProfileSection title="Notes"><div className="whitespace-pre-wrap text-sm text-neutral-700">{driver.notes || "—"}</div></ProfileSection></div>
      <section aria-labelledby={`${panelId}-statistics`}><h3 id={`${panelId}-statistics`} className="mb-2 font-semibold">Statistics</h3><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="Trips" value={stats.tripCount} /><Stat label="Legs" value={stats.legCount} /><Stat label="Distance" value={`${stats.totalDistance.toFixed(1)} km`} /><Stat label="Drive Time" value={stats.totalDriveTime} /><Stat label="Passenger instances" value={stats.passengerInstances} /><Stat label="First trip" value={stats.firstTrip || "—"} /><Stat label="Latest trip" value={stats.latestTrip || "—"} /></div></section>
      <section aria-labelledby={`${panelId}-recent`}><h3 id={`${panelId}-recent`} className="mb-2 font-semibold">Recent Trips</h3><div className="space-y-1">{stats.recentTrips.length ? stats.recentTrips.map((item) => <button key={`${item.vehicleId}-${item.trip.id}`} type="button" className="grid w-full grid-cols-2 gap-1 rounded-lg border border-neutral-200 bg-white p-2 text-left text-xs sm:grid-cols-5" onClick={() => onViewTrip(item)}><span>{item.trip.startDate}</span><span>{item.vehicleName}</span><span>{item.distance.toFixed(1)} km</span><span>{item.driveTime}</span><span>End KM {fmtOdo(item.endOdometer)}</span></button>) : <div className="text-sm text-neutral-500">No trips recorded.</div>}</div></section>
      <div className="flex flex-wrap gap-2"><Button onClick={() => setEditing(driver)} aria-label={`Edit ${driverDisplayName(driver)}`}>Edit</Button><Button onClick={() => onDuplicate(driver)} aria-label={`Duplicate ${driverDisplayName(driver)}`}>Duplicate</Button><Button onClick={() => onToggleActive(driver.id)}>{driver.active ? "Deactivate" : "Activate"}</Button><Button variant="danger" onClick={() => onDelete(driver)} disabled={stats.tripCount > 0}>Delete</Button></div>
    </div>}</article>; })}
  </div>{editing && <DriverEditor driver={editing} vehicles={vehicles} assignedVehicleId={editing.defaultVehicleId} onClose={() => setEditing(null)} onSave={(value) => { onSave(value); setEditing(null); }} />}</section>;
}

function ProfileSection({ title, children }) { return <section className="rounded-lg border border-neutral-200 bg-white p-3"><h3 className="mb-2 font-semibold text-neutral-800">{title}</h3><div className="space-y-2">{children}</div></section>; }
function DriverEditor({ driver, vehicles, assignedVehicleId, onClose, onSave }) { const [draft, setDraft] = useState(driver); const set = (field, value) => setDraft((current) => ({ ...current, [field]: value })); const section = (title, fields) => <fieldset className="rounded-xl border border-neutral-200 p-3"><legend className="px-1 font-semibold">{title}</legend><div className="grid gap-3 sm:grid-cols-2">{fields}</div></fieldset>; const input = (field, label, type = "text") => <label className="text-sm text-neutral-600">{label}<input type={type} className="ts-control mt-1" value={draft[field] || ""} onChange={(event) => set(field, event.target.value)} /></label>; return <ModalShell title={draft.id ? "Edit Driver Profile" : "Add Driver Profile"} onClose={onClose} maxWidth="48rem" footer={<><Button onClick={onClose}>Cancel</Button><Button variant="primary" disabled={!String(draft.fullName || "").trim()} onClick={() => onSave(draft)}>Save</Button></>}><div className="space-y-3">{section("Basic Information", [input("fullName", "Full name"), input("displayName", "Display name"), input("employeeNumber", "Employee number")])}{section("Contact", [input("phone", "Phone", "tel"), input("email", "Email", "email")])}{section("Licence", [input("licenceNumber", "Licence number"), input("licenceCountry", "Licence country"), input("licenceExpiry", "Licence expiry", "date")])}{section("Employment", [input("startDate", "Start date", "date")])}<fieldset className="rounded-xl border border-neutral-200 p-3"><legend className="px-1 font-semibold">Vehicle</legend><label className="text-sm text-neutral-600">Default vehicle<select className="ts-control mt-1" value={draft.defaultVehicleId || ""} onChange={(event) => set("defaultVehicleId", event.target.value)}><option value="">No default vehicle</option>{vehicles.filter((vehicle) => vehicle.active !== false || vehicle.id === assignedVehicleId).map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.name}{vehicle.active === false ? " (Inactive)" : ""}</option>)}</select></label></fieldset><fieldset className="rounded-xl border border-neutral-200 p-3"><legend className="px-1 font-semibold">Notes</legend><textarea className="ts-control" value={draft.notes || ""} onChange={(event) => set("notes", event.target.value)} /></fieldset></div></ModalShell>; }
