import { describe, expect, it } from "vitest";
import { deepEquivalent } from "./mergeIdentity.js";
import { createMergePlan } from "./mergePlanner.js";
import { validateApplicationPayload } from "./backupValidator.js";
import { clone, validApp } from "./testFixtures.js";

const NOW = "2026-07-11T12:00:00.000Z";
const plan = (current, imported, resolutions = {}) => createMergePlan(current, imported, { importedAt: NOW, resolutions });
const withoutActive = (data) => { data.activeTripByVehicle.v1 = null; return data; };
function addVehicle(data, vehicle) {
  data.vehicles.push(vehicle); data.tripsByVehicle[vehicle.id] = []; data.activeTripByVehicle[vehicle.id] = null; data.fuelByVehicle[vehicle.id] = []; data.washByVehicle[vehicle.id] = [];
}
const resolve = (first, decision) => ({ [first.unresolved[0].key]: decision });

describe("vehicle reconciliation", () => {
  it("adds a new vehicle", () => { const current = validApp(); const imported = validApp(); addVehicle(imported, { id: "v2", name: "Van" }); const result = plan(current, imported); expect(result.stats.vehicles.added).toBe(1); expect(result.candidate.vehicles.some((v) => v.id === "v2")).toBe(true); });
  it("skips the same identical vehicle ID", () => expect(plan(validApp(), validApp()).stats.vehicles.skipped).toBe(1));
  it("enriches compatible same-ID fields", () => { const current = validApp(); const imported = validApp(); imported.vehicles[0].vin = "VIN123"; const result = plan(current, imported); expect(result.stats.vehicles.updated).toBe(1); expect(result.candidate.vehicles[0].vin).toBe("VIN123"); });
  it("requires resolution for conflicting VINs", () => { const current = validApp(); const imported = validApp(); current.vehicles[0].vin = "A"; imported.vehicles[0].vin = "B"; const result = plan(current, imported); expect(result.conflicts[0]).toMatchObject({ type: "vehicles" }); expect(result.ready).toBe(false); });
  it("classifies different IDs with matching VIN as probable", () => { const current = validApp(); current.vehicles[0].vin = "ABC-1"; const imported = validApp(); imported.vehicles[0].id = "remote"; imported.vehicles[0].vin = "abc1"; imported.tripsByVehicle.remote = imported.tripsByVehicle.v1; imported.activeTripByVehicle.remote = imported.activeTripByVehicle.v1; imported.fuelByVehicle.remote = imported.fuelByVehicle.v1; imported.washByVehicle.remote = imported.washByVehicle.v1; delete imported.tripsByVehicle.v1; delete imported.activeTripByVehicle.v1; delete imported.fuelByVehicle.v1; delete imported.washByVehicle.v1; const result = plan(current, imported); expect(result.probableDuplicates[0]).toMatchObject({ type: "vehicles" }); });
  it("classifies compatible matching plates as probable", () => { const current = validApp(); current.vehicles[0].plate = "B-AB 123"; const imported = validApp(); imported.vehicles[0].id = "remote"; imported.vehicles[0].plate = "bab123"; imported.tripsByVehicle.remote = []; imported.activeTripByVehicle.remote = null; imported.fuelByVehicle.remote = []; imported.washByVehicle.remote = []; delete imported.tripsByVehicle.v1; delete imported.activeTripByVehicle.v1; delete imported.fuelByVehicle.v1; delete imported.washByVehicle.v1; expect(plan(current, imported).probableDuplicates[0].reason).toContain("plate"); });
  it("safely remaps an unrelated same-ID vehicle and dependents", () => { const current = validApp(); const imported = validApp(); current.vehicles[0].vin = "CURRENT"; imported.vehicles[0].vin = "REMOTE"; const first = plan(current, imported); const result = plan(current, imported, resolve(first, "remap")); const remapped = result.vehicleMap.v1; expect(remapped).toBe("v1-imported"); expect(result.candidate.tripsByVehicle[remapped][0].vehicleId).toBe(remapped); expect(result.candidate.fuelByVehicle[remapped]).toHaveLength(1); expect(result.candidate.washByVehicle[remapped]).toHaveLength(1); expect(validateApplicationPayload(result.candidate).ok).toBe(true); });
  it("maps probable vehicles and all dependent records when treated as same", () => { const current = withoutActive(validApp()); current.vehicles[0].vin = "VIN"; const imported = withoutActive(validApp()); imported.vehicles[0].id = "remote"; imported.vehicles[0].vin = "VIN"; imported.tripsByVehicle.remote = imported.tripsByVehicle.v1.map((trip) => ({ ...trip, id: "remote-trip", vehicleId: "remote", startDate: "2026-07-12" })); imported.fuelByVehicle.remote = imported.fuelByVehicle.v1.map((entry) => ({ ...entry, id: "remote-fuel", date: "2026-07-12" })); imported.washByVehicle.remote = imported.washByVehicle.v1.map((entry) => ({ ...entry, id: "remote-wash", date: "2026-07-12" })); imported.activeTripByVehicle.remote = null; delete imported.tripsByVehicle.v1; delete imported.fuelByVehicle.v1; delete imported.washByVehicle.v1; delete imported.activeTripByVehicle.v1; const first = plan(current, imported); const result = plan(current, imported, resolve(first, "same")); expect(result.vehicleMap.remote).toBe("v1"); expect(result.candidate.tripsByVehicle.v1.some((trip) => trip.vehicleId === "v1")).toBe(true); expect(result.candidate.fuelByVehicle.v1.some((entry) => entry.id === "remote-fuel")).toBe(true); });
});

describe("trip and leg merging", () => {
  it("adds a new trip with its legs", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.tripsByVehicle.v1.push({ ...clone(imported.tripsByVehicle.v1[0]), id: "t2", startDate: "2026-07-11", legs: [{ ...clone(imported.tripsByVehicle.v1[0].legs[0]), id: "l2" }] }); const result = plan(current, imported); expect(result.stats.trips.added).toBe(1); expect(result.candidate.tripsByVehicle.v1.find((trip) => trip.id === "t2").legs[0].id).toBe("l2"); });
  it("skips identical trips and legs", () => { const result = plan(withoutActive(validApp()), withoutActive(validApp())); expect(result.stats.trips.skipped).toBe(1); expect(result.stats.legs.skipped).toBe(1); });
  it("enriches a compatible trip", () => { const current = withoutActive(validApp()); current.tripsByVehicle.v1[0].notes = ""; const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].notes = "Details"; const result = plan(current, imported); expect(result.stats.trips.updated).toBe(1); expect(result.candidate.tripsByVehicle.v1[0].notes).toBe("Details"); });
  it("enriches a blank driver and additive passengers", () => { const current = withoutActive(validApp()); current.tripsByVehicle.v1[0].passengers = ["Ambassador"]; const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].driver = "Retro"; imported.tripsByVehicle.v1[0].passengers = ["Ambassador", "Security Officer"]; const result = plan(current, imported); expect(result.ready).toBe(true); expect(result.candidate.tripsByVehicle.v1[0]).toMatchObject({ driver: "Retro", passengers: ["Ambassador", "Security Officer"] }); });
  it("requires resolution for different nonblank drivers", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); current.tripsByVehicle.v1[0].driver = "Current"; imported.tripsByVehicle.v1[0].driver = "Imported"; expect(plan(current, imported).conflicts[0].reason).toContain("driver"); });
  it("requires resolution for ambiguous passenger replacement", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); current.tripsByVehicle.v1[0].passengers = ["A", "B"]; imported.tripsByVehicle.v1[0].passengers = ["A", "C"]; expect(plan(current, imported).conflicts[0].reason).toContain("passengers"); });
  it("keeps passenger enrichment idempotent and ordered", () => { const current = withoutActive(validApp()); current.tripsByVehicle.v1[0].passengers = ["A"]; const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].passengers = ["A", "B"]; const first = plan(current, imported).candidate; const second = plan(first, imported); expect(second.candidate.tripsByVehicle.v1[0].passengers).toEqual(["A", "B"]); expect(second.stats.trips.added).toBe(0); });
  it("requires resolution for conflicting trip dates", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].startDate = "2026-07-09"; expect(plan(current, imported).conflicts.some((item) => item.type === "trips")).toBe(true); });
  it("detects a probable duplicate trip", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].id = "remote-trip"; imported.tripsByVehicle.v1[0].legs[0].id = "remote-leg"; expect(plan(current, imported).probableDuplicates.some((item) => item.type === "trips")).toBe(true); });
  it("Keep Both generates a stable unique trip ID", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].startDate = "2026-07-09"; const first = plan(current, imported); const merged = plan(current, imported, resolve(first, "both")); expect(merged.candidate.tripsByVehicle.v1.some((trip) => trip.id === "t1-imported")).toBe(true); const repeated = plan(merged.candidate, imported); expect(repeated.stats.trips.added).toBe(0); });
  it("appends a new leg", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].legs.push({ id: "l2", odoStart: 5, odoEnd: 6, km: 1 }); const result = plan(current, imported); expect(result.stats.legs.added).toBe(1); expect(result.candidate.tripsByVehicle.v1[0].legs).toHaveLength(2); });
  it("requires resolution for conflicting same-ID odometers", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].legs[0].odoEnd = 99; const result = plan(current, imported); expect(result.conflicts.some((item) => item.type === "legs")).toBe(true); });
  it("detects probable duplicate legs", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].legs[0].id = "other-leg"; const result = plan(current, imported); expect(result.probableDuplicates.some((item) => item.type === "legs") || result.probableDuplicates.some((item) => item.type === "trips")).toBe(true); });
});

describe("fuel, wash, templates, and active trips", () => {
  it("skips identical fuel/wash entries and adds new ones", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.fuelByVehicle.v1.push({ ...clone(imported.fuelByVehicle.v1[0]), id: "f2", date: "2026-07-11" }); imported.washByVehicle.v1.push({ ...clone(imported.washByVehicle.v1[0]), id: "w2", date: "2026-07-11" }); const result = plan(current, imported); expect(result.stats.fuel).toMatchObject({ added: 1, skipped: 1 }); expect(result.stats.wash).toMatchObject({ added: 1, skipped: 1 }); });
  it("requires decisions for conflicting same-ID fuel and wash entries", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.fuelByVehicle.v1[0].liters = 99; imported.washByVehicle.v1[0].cost = 99; const result = plan(current, imported); expect(result.conflicts.map((item) => item.type)).toEqual(expect.arrayContaining(["fuel", "wash"])); });
  it("detects probable fuel and wash duplicates", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.fuelByVehicle.v1[0].id = "other-f"; imported.washByVehicle.v1[0].id = "other-w"; const types = plan(current, imported).probableDuplicates.map((item) => item.type); expect(types).toEqual(expect.arrayContaining(["fuel", "wash"])); });
  it("skips identical templates and adds a same-name template with different data explicitly", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.templates.push({ id: "tpl2", type: "trip", name: "Work", data: { title: "Different" } }); const result = plan(current, imported); expect(result.stats.templates).toMatchObject({ added: 1, skipped: 1 }); });
  it("adds an imported-only active trip", () => { const current = withoutActive(validApp()); const imported = validApp(); expect(plan(current, imported).stats.activeTrips.added).toBe(1); });
  it("skips identical active trips", () => expect(plan(validApp(), validApp()).stats.activeTrips.skipped).toBe(1));
  it("requires and applies active-trip resolution", () => { const current = validApp(); const imported = validApp(); imported.activeTripByVehicle.v1.title = "Different"; const first = plan(current, imported); expect(first.conflicts.some((item) => item.type === "activeTrips")).toBe(true); const result = plan(current, imported, resolve(first, "imported")); expect(result.candidate.activeTripByVehicle.v1.title).toBe("Different"); expect(result.ready).toBe(true); });
  it("can convert the imported active trip to a completed draft", () => { const current = validApp(); const imported = validApp(); imported.activeTripByVehicle.v1.id = "remote-active"; imported.activeTripByVehicle.v1.title = "Remote"; const first = plan(current, imported); const result = plan(current, imported, resolve(first, "complete")); expect(result.candidate.activeTripByVehicle.v1.id).toBe("active-1"); expect(result.candidate.tripsByVehicle.v1.some((trip) => trip.id === "remote-active" && trip.status === "finished")).toBe(true); });
});

describe("idempotency and device convergence", () => {
  it("merging the same additive backup twice adds nothing the second time", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.tripsByVehicle.v1.push({ id: "phone-trip", vehicleId: "v1", title: "Phone", purpose: "", startDate: "2026-07-11", status: "finished", legs: [] }); const first = plan(current, imported); const second = plan(first.candidate, imported); expect(second.stats.trips.added).toBe(0); expect(second.candidate.tripsByVehicle.v1.filter((trip) => trip.id === "phone-trip")).toHaveLength(1); });
  it("keeps generated IDs stable after commit", () => { const current = withoutActive(validApp()); const imported = withoutActive(validApp()); imported.tripsByVehicle.v1[0].startDate = "2026-07-09"; const first = plan(current, imported); const committed = plan(current, imported, resolve(first, "both")).candidate; const repeated = plan(committed, imported); expect(repeated.candidate.tripsByVehicle.v1.map((trip) => trip.id)).toEqual(committed.tripsByVehicle.v1.map((trip) => trip.id)); });
  it("converges independently changed phone and PC datasets without duplication", () => { const shared = withoutActive(validApp()); const phone = clone(shared); const pc = clone(shared); phone.tripsByVehicle.v1.push({ id: "phone-only", vehicleId: "v1", title: "Phone", purpose: "", startDate: "2026-07-11", status: "finished", legs: [] }); pc.tripsByVehicle.v1.push({ id: "pc-only", vehicleId: "v1", title: "PC", purpose: "", startDate: "2026-07-12", status: "finished", legs: [] }); const mergedPc = plan(pc, phone).candidate; const mergedPhone = plan(phone, mergedPc).candidate; expect(new Set(mergedPc.tripsByVehicle.v1.map((trip) => trip.id))).toEqual(new Set(["t1", "phone-only", "pc-only"])); expect(new Set(mergedPhone.tripsByVehicle.v1.map((trip) => trip.id))).toEqual(new Set(["t1", "phone-only", "pc-only"])); expect(deepEquivalent(mergedPc, mergedPhone)).toBe(true); });
});
