import { Badge, Button, EmptyState } from "../ui/index.jsx";

const formatNumber = (value, digits = 1) => Number(value || 0).toFixed(digits);
const formatTimestamp = (value) => {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "" : date.toLocaleString();
};

function MetricCard({ label, value, detail, onClick, children }) {
  return <button type="button" className="ts-dashboard-metric" onClick={onClick}><span>{label}</span>{value != null && <strong>{value}</strong>}{children}<small>{detail}</small></button>;
}

function ActiveCommand({ data, persistenceStatus, onResume, onStart, onAddVehicle }) {
  if (!data.vehicle) return <section className="ts-dashboard-command"><EmptyState title="No vehicle configured" description="Add a vehicle to begin recording operational journeys." action={<Button variant="primary" onClick={onAddVehicle}>Add Vehicle</Button>} /></section>;
  if (!data.activeTrip) return <section className="ts-dashboard-command"><div><div className="ts-dashboard-eyebrow">Selected vehicle · {data.vehicle.name}</div><h2>No active trip</h2><p>Start a journey using the existing Operations workflow.</p></div><Button variant="primary" onClick={onStart}>Start Trip</Button></section>;

  const trip = data.activeTrip;
  const started = trip.startedAt ? formatTimestamp(trip.startedAt) : "";
  return <section className="ts-dashboard-command ts-dashboard-command--active"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge variant="success">Active</Badge><span className="ts-dashboard-eyebrow">{trip.vehicleName} · {trip.startDate}</span></div><h2>{trip.title}</h2>{trip.route ? <div className="ts-dashboard-route">{trip.route}</div> : <div className="ts-dashboard-muted">No leg has yet been recorded.</div>}{trip.latestLegSummary && <div className="ts-dashboard-latest-leg">Latest leg: {trip.latestLegSummary.route} · {trip.latestLegSummary.journey}</div>}<div className="ts-dashboard-command__meta"><span>{trip.legCount} {trip.legCount === 1 ? "leg" : "legs"}</span>{started && <span>Started: {started}</span>}{trip.driver && <span>Driver: {trip.driver}</span>}{trip.passengers.length > 0 && <span>Passengers: {trip.passengers.join(", ")}</span>}{trip.purpose && <span>Purpose: {trip.purpose}</span>}<span>Storage: {persistenceStatus}</span></div></div><div className="ts-dashboard-command__action"><span>Distance</span><strong>{formatNumber(trip.distance)} km</strong><Button variant="primary" onClick={onResume}>Resume Trip</Button></div></section>;
}

export function Dashboard({ data, persistenceStatus, onStartTrip, onResumeTrip, onOpenHistory, onOpenFuel, onOpenWash, onOpenReports, onAddVehicle, onOpenJourney }) {
  return <main className="ts-dashboard" aria-labelledby="dashboard-heading"><header className="ts-dashboard-heading"><div><div className="ts-dashboard-eyebrow">TripIt operational overview</div><h1 id="dashboard-heading">Dashboard</h1><p>{data.vehicle ? `${data.vehicle.name}${data.vehicle.plate ? ` · ${data.vehicle.plate}` : ""} · ${data.month}` : "Fleet setup required"}</p></div>{data.vehicle && <Badge variant="accent">Selected vehicle</Badge>}</header>
    <ActiveCommand data={data} persistenceStatus={persistenceStatus} onResume={onResumeTrip} onStart={onStartTrip} onAddVehicle={onAddVehicle} />
    {data.metrics && <section className="ts-dashboard-metrics" aria-label="Current month metrics"><MetricCard label="Completed journeys" value={String(data.metrics.completedJourneys)} detail={`${data.metrics.completedLegs} completed legs · ${data.month}`} onClick={onOpenHistory} /><MetricCard label="Distance" value={`${formatNumber(data.metrics.distance)} km`} detail={`Completed journeys · ${data.month}`} onClick={onOpenHistory} /><MetricCard label="Fuel volume" value={`${formatNumber(data.metrics.fuelLitres, 2)} L`} detail={`${data.metrics.fuelEntries} fuel ${data.metrics.fuelEntries === 1 ? "entry" : "entries"}`} onClick={onOpenFuel} /><MetricCard label="Fuel spend" detail={data.metrics.fuelSpend.length ? `${data.month} · grouped by currency` : "No fuel spend recorded"} onClick={onOpenFuel}>{data.metrics.fuelSpend.length > 0 && <span className="ts-dashboard-money">{data.metrics.fuelSpend.map(({ currency, total }) => <strong key={currency}>{Number(total).toFixed(2)} {currency}</strong>)}</span>}</MetricCard></section>}
    {data.vehicle && <div className="ts-dashboard-grid"><section className="ts-dashboard-panel ts-dashboard-activity" aria-labelledby="recent-journeys-heading"><div className="ts-dashboard-panel__header"><div><div className="ts-dashboard-eyebrow">Activity</div><h2 id="recent-journeys-heading">Recent journeys</h2></div><Button variant="ghost" onClick={onOpenHistory}>View history</Button></div>{data.recentJourneys.length ? <div className="ts-dashboard-journeys">{data.recentJourneys.map((journey) => <button type="button" className="ts-dashboard-journey" key={journey.id} onClick={() => onOpenJourney(journey)}><span className="min-w-0"><strong>{journey.title}</strong><span>{journey.route || "No route recorded"}</span><small>{journey.startDate} · {journey.vehicleName}{journey.drivers.length ? ` · ${journey.drivers.join(", ")}` : ""}{journey.passengerCount ? ` · ${journey.passengerCount} passengers` : ""}</small></span><b>{formatNumber(journey.distance)} km</b></button>)}</div> : <EmptyState title="No completed journeys" description="Completed trips for the selected vehicle will appear here." />}</section>
      <aside className="space-y-3"><section className="ts-dashboard-panel" aria-labelledby="vehicle-overview-heading"><div className="ts-dashboard-eyebrow">Selected asset</div><h2 id="vehicle-overview-heading">Vehicle overview</h2><dl className="ts-dashboard-details"><div><dt>Vehicle</dt><dd>{data.vehicleOverview.name}</dd></div><div><dt>Make / model</dt><dd>{data.vehicleOverview.makeModel || "—"}</dd></div><div><dt>Registration</dt><dd>{data.vehicleOverview.plate || "—"}</dd></div><div><dt>Trip status</dt><dd>{data.vehicleOverview.hasActiveTrip ? "Active trip" : "No active trip"}</dd></div><div><dt>Current month</dt><dd>{data.vehicleOverview.monthJourneys} journeys · {formatNumber(data.vehicleOverview.monthDistance)} km</dd></div><div><dt>Latest fuel</dt><dd>{data.vehicleOverview.latestFuel?.date || "No fuel activity"}</dd></div>{data.vehicleOverview.latestFuelOdometer != null && <div><dt>Latest fuel odometer</dt><dd>{data.vehicleOverview.latestFuelOdometer} km</dd></div>}<div><dt>Latest wash</dt><dd>{data.vehicleOverview.latestWash?.date || "No wash activity"}</dd></div></dl></section>
        <section className="ts-dashboard-panel" aria-labelledby="quick-actions-heading"><div className="ts-dashboard-eyebrow">Workflows</div><h2 id="quick-actions-heading">Quick actions</h2><div className="ts-dashboard-actions"><Button variant="primary" onClick={data.activeTrip ? onResumeTrip : onStartTrip}>{data.activeTrip ? "Resume Trip" : "Start Trip"}</Button><Button onClick={onOpenFuel}>Add Fuel</Button><Button onClick={onOpenWash}>Add Wash</Button><Button onClick={onOpenReports}>Reports</Button><Button variant="ghost" onClick={onAddVehicle}>Add Vehicle</Button></div></section></aside></div>}
  </main>;
}
